export const TIPOS_COMPROBANTE = [
  { codigo: 1, descripcion: 'Factura A' },
  { codigo: 2, descripcion: 'Nota de Débito A' },
  { codigo: 3, descripcion: 'Nota de Crédito A' },
  { codigo: 4, descripcion: 'Recibo A' },
  { codigo: 5, descripcion: 'Nota de Venta al Contado A' },
  { codigo: 6, descripcion: 'Factura B' },
  { codigo: 7, descripcion: 'Nota de Débito B' },
  { codigo: 8, descripcion: 'Nota de Crédito B' },
  { codigo: 9, descripcion: 'Recibo B' },
  { codigo: 10, descripcion: 'Nota de Venta al Contado B' },
  { codigo: 11, descripcion: 'Factura C' },
  { codigo: 12, descripcion: 'Nota de Débito C' },
  { codigo: 13, descripcion: 'Nota de Crédito C' },
  { codigo: 15, descripcion: 'Recibo C' },
  { codigo: 19, descripcion: 'Factura de exportación' },
  { codigo: 20, descripcion: 'Nota de Débito por operaciones con el exterior' },
  { codigo: 21, descripcion: 'Nota de Crédito por operaciones con el exterior' },
  { codigo: 22, descripcion: 'Factura - Compra de bienes usados' },
  { codigo: 23, descripcion: 'Factura A - MIPE' },
  { codigo: 24, descripcion: 'Nota de Débito A - MIPE' },
  { codigo: 25, descripcion: 'Nota de Crédito A - MIPE' },
  { codigo: 26, descripcion: 'Factura B - MIPE' },
  { codigo: 27, descripcion: 'Nota de Débito B - MIPE' },
  { codigo: 28, descripcion: 'Nota de Crédito B - MIPE' },
  { codigo: 29, descripcion: 'Factura C - MIPE' },
  { codigo: 30, descripcion: 'Nota de Débito C - MIPE' },
  { codigo: 31, descripcion: 'Nota de Crédito C - MIPE' },
  { codigo: 34, descripcion: 'Comprobante A del art. 3 R.G. 1415' },
  { codigo: 35, descripcion: 'Comprobante B del art. 3 R.G. 1415' },
  { codigo: 36, descripcion: 'Comprobante C del art. 3 R.G. 1415' },
  { codigo: 39, descripcion: 'Otros comprobantes A' },
  { codigo: 40, descripcion: 'Otros comprobantes B' },
  { codigo: 41, descripcion: 'Otros comprobantes C' },
  { codigo: 43, descripcion: 'Liquidación A' },
  { codigo: 44, descripcion: 'Liquidación B' },
  { codigo: 45, descripcion: 'Liquidación C' },
  { codigo: 46, descripcion: 'Factura de crédito electrónica MiPyME A' },
  { codigo: 47, descripcion: 'Nota de Débito de crédito electrónica MiPyME A' },
  { codigo: 48, descripcion: 'Nota de Crédito de crédito electrónica MiPyME A' },
  { codigo: 49, descripcion: 'Factura de crédito electrónica MiPyME B' },
  { codigo: 50, descripcion: 'Nota de Débito de crédito electrónica MiPyME B' },
  { codigo: 51, descripcion: 'Nota de Crédito de crédito electrónica MiPyME B' },
];